// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace yigame.epoker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.Serialization;
    
    
    public class CoreGameSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "EPokerRepositoryKernelScene";
            }
        }
        
        public virtual CoreGameSceneSettings Settings {
            get {
                return _SettingsObject as CoreGameSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
    
    public class CoreGameSceneLoaderBase : SceneLoader<CoreGameScene> {
        
        protected override IEnumerator LoadScene(CoreGameScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(CoreGameScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
    
    public class OutOfGameSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "EPokerRepositoryKernelScene";
            }
        }
        
        public virtual OutOfGameSceneSettings Settings {
            get {
                return _SettingsObject as OutOfGameSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
    
    public class OutOfGameSceneLoaderBase : SceneLoader<OutOfGameScene> {
        
        protected override IEnumerator LoadScene(OutOfGameScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(OutOfGameScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
    
    public class PlayerTestSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "EPokerRepositoryKernelScene";
            }
        }
        
        public virtual PlayerTestSceneSettings Settings {
            get {
                return _SettingsObject as PlayerTestSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
    
    public class PlayerTestSceneLoaderBase : SceneLoader<PlayerTestScene> {
        
        protected override IEnumerator LoadScene(PlayerTestScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(PlayerTestScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
}
