// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace yigame.epoker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.Serialization;
    
    
    public partial class ResetPlayerCountCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class RootMatchBeganCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class SimulateMatchBeganCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class CreateDeckToPileCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class DealPileCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class QuitCoreGameCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class PlayerReadyCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class PlayerCancelCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class MatchBeganCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class BeganToPlayCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class BeganToWaitCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class TurnOnCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class TurnOffCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class WinCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class OverCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class InitOKCommand : uFrame.MVVM.ViewModelCommand {
    }
}
