// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace yigame.epoker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.IOC;
    using uFrame.MVVM;
    using uFrame.Serialization;
    using yigame.epoker;
    using UniRx;
    
    
    public class CoreGameRootControllerBase : uFrame.MVVM.Controller {
        
        private uFrame.MVVM.IViewModelManager _CoreGameRootViewModelManager;
        
        private CoreGameRootViewModel _CoreGameRoot;
        
        [uFrame.IOC.InjectAttribute("CoreGameRoot")]
        public uFrame.MVVM.IViewModelManager CoreGameRootViewModelManager {
            get {
                return _CoreGameRootViewModelManager;
            }
            set {
                _CoreGameRootViewModelManager = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute("CoreGameRoot")]
        public CoreGameRootViewModel CoreGameRoot {
            get {
                return _CoreGameRoot;
            }
            set {
                _CoreGameRoot = value;
            }
        }
        
        public IEnumerable<CoreGameRootViewModel> CoreGameRootViewModels {
            get {
                return CoreGameRootViewModelManager.OfType<CoreGameRootViewModel>();
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeCoreGameRoot(((CoreGameRootViewModel)(viewModel)));
        }
        
        public virtual CoreGameRootViewModel CreateCoreGameRoot() {
            return ((CoreGameRootViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModel CreateEmpty() {
            return new CoreGameRootViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeCoreGameRoot(CoreGameRootViewModel viewModel) {
            // This is called when a CoreGameRootViewModel is created
            CoreGameRootViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            CoreGameRootViewModelManager.Remove(viewModel);
        }
    }
    
    public class BackGroundControllerBase : uFrame.MVVM.Controller {
        
        private uFrame.MVVM.IViewModelManager _BackGroundViewModelManager;
        
        private CoreGameRootViewModel _CoreGameRoot;
        
        [uFrame.IOC.InjectAttribute("BackGround")]
        public uFrame.MVVM.IViewModelManager BackGroundViewModelManager {
            get {
                return _BackGroundViewModelManager;
            }
            set {
                _BackGroundViewModelManager = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute("CoreGameRoot")]
        public CoreGameRootViewModel CoreGameRoot {
            get {
                return _CoreGameRoot;
            }
            set {
                _CoreGameRoot = value;
            }
        }
        
        public IEnumerable<BackGroundViewModel> BackGroundViewModels {
            get {
                return BackGroundViewModelManager.OfType<BackGroundViewModel>();
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeBackGround(((BackGroundViewModel)(viewModel)));
        }
        
        public virtual BackGroundViewModel CreateBackGround() {
            return ((BackGroundViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModel CreateEmpty() {
            return new BackGroundViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeBackGround(BackGroundViewModel viewModel) {
            // This is called when a BackGroundViewModel is created
            BackGroundViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            BackGroundViewModelManager.Remove(viewModel);
        }
    }
    
    public class CardControllerBase : uFrame.MVVM.Controller {
        
        private uFrame.MVVM.IViewModelManager _CardViewModelManager;
        
        private CoreGameRootViewModel _CoreGameRoot;
        
        [uFrame.IOC.InjectAttribute("Card")]
        public uFrame.MVVM.IViewModelManager CardViewModelManager {
            get {
                return _CardViewModelManager;
            }
            set {
                _CardViewModelManager = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute("CoreGameRoot")]
        public CoreGameRootViewModel CoreGameRoot {
            get {
                return _CoreGameRoot;
            }
            set {
                _CoreGameRoot = value;
            }
        }
        
        public IEnumerable<CardViewModel> CardViewModels {
            get {
                return CardViewModelManager.OfType<CardViewModel>();
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeCard(((CardViewModel)(viewModel)));
        }
        
        public virtual CardViewModel CreateCard() {
            return ((CardViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModel CreateEmpty() {
            return new CardViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeCard(CardViewModel viewModel) {
            // This is called when a CardViewModel is created
            CardViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            CardViewModelManager.Remove(viewModel);
        }
    }
}
