// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace yigame.epoker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public enum PlayerNodeMode {
        
        Waiting,
        
        Playing,
        
        WinWaiting,
    }
    
    public enum CardSelectMode {
        
        None,
        
        Select,
        
        Deselect,
    }
    
    public enum GameMode {
        
        m_2p_r40c,
        
        m_3p_spade_ace,
    }
}
