// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace yigame.epoker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.Serialization;
    
    
    public class OpenCoreGameBase : object {
    }
    
    public class CloseCoreGameBase : object {
    }
    
    public class OnCoreGameEventBase : object {
        
        private Byte _EventCode;
        
        private Object _EventContent;
        
        public Byte EventCode {
            get {
                return _EventCode;
            }
            set {
                _EventCode = value;
            }
        }
        
        public Object EventContent {
            get {
                return _EventContent;
            }
            set {
                _EventContent = value;
            }
        }
    }
}
