// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace yigame.epoker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using yigame.epoker;
    
    
    public class CoreGameLoaderBase : uFrame.Kernel.SystemLoader {
        
        private CoreGameRootViewModel _CoreGameRoot;
        
        private CoreGameRootController _CoreGameRootController;
        
        [uFrame.IOC.InjectAttribute("CoreGameRoot")]
        public virtual CoreGameRootViewModel CoreGameRoot {
            get {
                if (this._CoreGameRoot == null) {
                    this._CoreGameRoot = this.CreateViewModel<CoreGameRootViewModel>( "CoreGameRoot");
                }
                return _CoreGameRoot;
            }
            set {
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual CoreGameRootController CoreGameRootController {
            get {
                if (_CoreGameRootController==null) {
                    _CoreGameRootController = Container.CreateInstance(typeof(CoreGameRootController)) as CoreGameRootController;;
                }
                return _CoreGameRootController;
            }
            set {
                _CoreGameRootController = value;
            }
        }
        
        public override void Load() {
            Container.RegisterViewModelManager<CoreGameRootViewModel>(new ViewModelManager<CoreGameRootViewModel>());
            Container.RegisterController<CoreGameRootController>(CoreGameRootController);
            Container.RegisterViewModel<CoreGameRootViewModel>(CoreGameRoot, "CoreGameRoot");
        }
    }
}
