// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace yigame.epoker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.Serialization;
    using UnityEngine;
    using UniRx;
    using yigame.epoker;
    
    
    public partial class CoreGameRootViewModelBase : uFrame.MVVM.ViewModel {
        
        private P<BackGroundViewModel> _BackGroundProperty;
        
        private P<Int32> _PlayerCountProperty;
        
        private ModelCollection<PlayerViewModel> _PlayerCollection;
        
        private Signal<ResetPlayerCountCommand> _ResetPlayerCount;
        
        private Signal<RootMatchBeganCommand> _RootMatchBegan;
        
        private Signal<SimulateMatchBeganCommand> _SimulateMatchBegan;
        
        public CoreGameRootViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual P<BackGroundViewModel> BackGroundProperty {
            get {
                return _BackGroundProperty;
            }
            set {
                _BackGroundProperty = value;
            }
        }
        
        public virtual P<Int32> PlayerCountProperty {
            get {
                return _PlayerCountProperty;
            }
            set {
                _PlayerCountProperty = value;
            }
        }
        
        public virtual BackGroundViewModel BackGround {
            get {
                return BackGroundProperty.Value;
            }
            set {
                BackGroundProperty.Value = value;
            }
        }
        
        public virtual Int32 PlayerCount {
            get {
                return PlayerCountProperty.Value;
            }
            set {
                PlayerCountProperty.Value = value;
            }
        }
        
        public virtual ModelCollection<PlayerViewModel> PlayerCollection {
            get {
                return _PlayerCollection;
            }
            set {
                _PlayerCollection = value;
            }
        }
        
        public virtual Signal<ResetPlayerCountCommand> ResetPlayerCount {
            get {
                return _ResetPlayerCount;
            }
            set {
                _ResetPlayerCount = value;
            }
        }
        
        public virtual Signal<RootMatchBeganCommand> RootMatchBegan {
            get {
                return _RootMatchBegan;
            }
            set {
                _RootMatchBegan = value;
            }
        }
        
        public virtual Signal<SimulateMatchBeganCommand> SimulateMatchBegan {
            get {
                return _SimulateMatchBegan;
            }
            set {
                _SimulateMatchBegan = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            this.ResetPlayerCount = new Signal<ResetPlayerCountCommand>(this);
            this.RootMatchBegan = new Signal<RootMatchBeganCommand>(this);
            this.SimulateMatchBegan = new Signal<SimulateMatchBeganCommand>(this);
            _BackGroundProperty = new P<BackGroundViewModel>(this, "BackGround");
            _PlayerCountProperty = new P<Int32>(this, "PlayerCount");
            _PlayerCollection = new ModelCollection<PlayerViewModel>(this, "PlayerCollection");
        }
        
        public virtual void ExecuteResetPlayerCount(Int32 argument) {
            this.ResetPlayerCount.OnNext(new ResetPlayerCountCommand(){Argument = argument});
        }
        
        public virtual void ExecuteRootMatchBegan() {
            this.RootMatchBegan.OnNext(new RootMatchBeganCommand());
        }
        
        public virtual void ExecuteSimulateMatchBegan() {
            this.SimulateMatchBegan.OnNext(new SimulateMatchBeganCommand());
        }
        
        public override void Read(ISerializerStream stream) {
            base.Read(stream);
            		if (stream.DeepSerialize) this.BackGround = stream.DeserializeObject<BackGroundViewModel>("BackGround");;
            this.PlayerCount = stream.DeserializeInt("PlayerCount");;
            if (stream.DeepSerialize) {
                this.PlayerCollection.Clear();
                this.PlayerCollection.AddRange(stream.DeserializeObjectArray<PlayerViewModel>("PlayerCollection"));
            }
        }
        
        public override void Write(ISerializerStream stream) {
            base.Write(stream);
            if (stream.DeepSerialize) stream.SerializeObject("BackGround", this.BackGround);;
            stream.SerializeInt("PlayerCount", this.PlayerCount);
            if (stream.DeepSerialize) stream.SerializeArray("PlayerCollection", this.PlayerCollection);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
            base.FillCommands(list);
            list.Add(new ViewModelCommandInfo("ResetPlayerCount", ResetPlayerCount) { ParameterType = typeof(Int32) });
            list.Add(new ViewModelCommandInfo("RootMatchBegan", RootMatchBegan) { ParameterType = typeof(void) });
            list.Add(new ViewModelCommandInfo("SimulateMatchBegan", SimulateMatchBegan) { ParameterType = typeof(void) });
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_BackGroundProperty, true, false, false, false));
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_PlayerCountProperty, false, false, false, false));
            list.Add(new ViewModelPropertyInfo(_PlayerCollection, true, true, false, false));
        }
    }
    
    public partial class CoreGameRootViewModel {
        
        public CoreGameRootViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
    
    public partial class BackGroundViewModelBase : uFrame.MVVM.ViewModel {
        
        public BackGroundViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public override void Bind() {
            base.Bind();
        }
        
        public override void Read(ISerializerStream stream) {
            base.Read(stream);
        }
        
        public override void Write(ISerializerStream stream) {
            base.Write(stream);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
            base.FillCommands(list);
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
        }
    }
    
    public partial class BackGroundViewModel {
        
        public BackGroundViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
    
    public partial class CardViewModelBase : uFrame.MVVM.ViewModel {
        
        private P<CardInfo> _InfoProperty;
        
        private P<CardFace> _FaceProperty;
        
        private P<CardPlace> _PlaceProperty;
        
        public CardViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual P<CardInfo> InfoProperty {
            get {
                return _InfoProperty;
            }
            set {
                _InfoProperty = value;
            }
        }
        
        public virtual P<CardFace> FaceProperty {
            get {
                return _FaceProperty;
            }
            set {
                _FaceProperty = value;
            }
        }
        
        public virtual P<CardPlace> PlaceProperty {
            get {
                return _PlaceProperty;
            }
            set {
                _PlaceProperty = value;
            }
        }
        
        public virtual CardInfo Info {
            get {
                return InfoProperty.Value;
            }
            set {
                InfoProperty.Value = value;
            }
        }
        
        public virtual CardFace Face {
            get {
                return FaceProperty.Value;
            }
            set {
                FaceProperty.Value = value;
            }
        }
        
        public virtual CardPlace Place {
            get {
                return PlaceProperty.Value;
            }
            set {
                PlaceProperty.Value = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            _InfoProperty = new P<CardInfo>(this, "Info");
            _FaceProperty = new P<CardFace>(this, "Face");
            _PlaceProperty = new P<CardPlace>(this, "Place");
        }
        
        public override void Read(ISerializerStream stream) {
            base.Read(stream);
            this.Face = (CardFace)stream.DeserializeInt("Face");;
            this.Place = (CardPlace)stream.DeserializeInt("Place");;
        }
        
        public override void Write(ISerializerStream stream) {
            base.Write(stream);
            stream.SerializeInt("Face", (int)this.Face);;
            stream.SerializeInt("Place", (int)this.Place);;
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
            base.FillCommands(list);
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_InfoProperty, false, false, false, false));
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_FaceProperty, false, false, true, false));
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_PlaceProperty, false, false, true, false));
        }
    }
    
    public partial class CardViewModel {
        
        public CardViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
    
    public partial class PlayerViewModelBase : uFrame.MVVM.ViewModel {
        
        private PlayerStatus _StatusProperty;
        
        private P<String> _IdProperty;
        
        private P<String> _PosIdProperty;
        
        private ModelCollection<CardViewModel> _HandCards;
        
        private Signal<PlayerReadyCommand> _PlayerReady;
        
        private Signal<PlayerCancelCommand> _PlayerCancel;
        
        private Signal<MatchBeganCommand> _MatchBegan;
        
        private Signal<BeganToPlayCommand> _BeganToPlay;
        
        private Signal<BeganToWaitCommand> _BeganToWait;
        
        private Signal<TurnOnCommand> _TurnOn;
        
        private Signal<TurnOffCommand> _TurnOff;
        
        private Signal<WinCommand> _Win;
        
        private Signal<OverCommand> _Over;
        
        private Signal<InitOKCommand> _InitOK;
        
        public PlayerViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual PlayerStatus StatusProperty {
            get {
                return _StatusProperty;
            }
            set {
                _StatusProperty = value;
            }
        }
        
        public virtual Invert.StateMachine.State Status {
            get {
                return StatusProperty.Value;
            }
            set {
                StatusProperty.Value = value;
            }
        }
        
        public virtual P<String> IdProperty {
            get {
                return _IdProperty;
            }
            set {
                _IdProperty = value;
            }
        }
        
        public virtual P<String> PosIdProperty {
            get {
                return _PosIdProperty;
            }
            set {
                _PosIdProperty = value;
            }
        }
        
        public virtual String Id {
            get {
                return IdProperty.Value;
            }
            set {
                IdProperty.Value = value;
            }
        }
        
        public virtual String PosId {
            get {
                return PosIdProperty.Value;
            }
            set {
                PosIdProperty.Value = value;
            }
        }
        
        public virtual ModelCollection<CardViewModel> HandCards {
            get {
                return _HandCards;
            }
            set {
                _HandCards = value;
            }
        }
        
        public virtual Signal<PlayerReadyCommand> PlayerReady {
            get {
                return _PlayerReady;
            }
            set {
                _PlayerReady = value;
            }
        }
        
        public virtual Signal<PlayerCancelCommand> PlayerCancel {
            get {
                return _PlayerCancel;
            }
            set {
                _PlayerCancel = value;
            }
        }
        
        public virtual Signal<MatchBeganCommand> MatchBegan {
            get {
                return _MatchBegan;
            }
            set {
                _MatchBegan = value;
            }
        }
        
        public virtual Signal<BeganToPlayCommand> BeganToPlay {
            get {
                return _BeganToPlay;
            }
            set {
                _BeganToPlay = value;
            }
        }
        
        public virtual Signal<BeganToWaitCommand> BeganToWait {
            get {
                return _BeganToWait;
            }
            set {
                _BeganToWait = value;
            }
        }
        
        public virtual Signal<TurnOnCommand> TurnOn {
            get {
                return _TurnOn;
            }
            set {
                _TurnOn = value;
            }
        }
        
        public virtual Signal<TurnOffCommand> TurnOff {
            get {
                return _TurnOff;
            }
            set {
                _TurnOff = value;
            }
        }
        
        public virtual Signal<WinCommand> Win {
            get {
                return _Win;
            }
            set {
                _Win = value;
            }
        }
        
        public virtual Signal<OverCommand> Over {
            get {
                return _Over;
            }
            set {
                _Over = value;
            }
        }
        
        public virtual Signal<InitOKCommand> InitOK {
            get {
                return _InitOK;
            }
            set {
                _InitOK = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            this.PlayerReady = new Signal<PlayerReadyCommand>(this);
            this.PlayerCancel = new Signal<PlayerCancelCommand>(this);
            this.MatchBegan = new Signal<MatchBeganCommand>(this);
            this.BeganToPlay = new Signal<BeganToPlayCommand>(this);
            this.BeganToWait = new Signal<BeganToWaitCommand>(this);
            this.TurnOn = new Signal<TurnOnCommand>(this);
            this.TurnOff = new Signal<TurnOffCommand>(this);
            this.Win = new Signal<WinCommand>(this);
            this.Over = new Signal<OverCommand>(this);
            this.InitOK = new Signal<InitOKCommand>(this);
            _IdProperty = new P<String>(this, "Id");
            _PosIdProperty = new P<String>(this, "PosId");
            _HandCards = new ModelCollection<CardViewModel>(this, "HandCards");
            _StatusProperty = new PlayerStatus(this, "Status");
            PlayerReady.Subscribe(_ => StatusProperty.PlayerReady.OnNext(true));
            PlayerCancel.Subscribe(_ => StatusProperty.PlayerCancel.OnNext(true));
            MatchBegan.Subscribe(_ => StatusProperty.MatchBegan.OnNext(true));
            BeganToPlay.Subscribe(_ => StatusProperty.BeganToPlay.OnNext(true));
            BeganToWait.Subscribe(_ => StatusProperty.BeganToWait.OnNext(true));
            TurnOn.Subscribe(_ => StatusProperty.TurnOn.OnNext(true));
            TurnOff.Subscribe(_ => StatusProperty.TurnOff.OnNext(true));
            Win.Subscribe(_ => StatusProperty.Win.OnNext(true));
            Over.Subscribe(_ => StatusProperty.Over.OnNext(true));
            InitOK.Subscribe(_ => StatusProperty.InitOK.OnNext(true));
        }
        
        public virtual void ExecutePlayerReady() {
            this.PlayerReady.OnNext(new PlayerReadyCommand());
        }
        
        public virtual void ExecutePlayerCancel() {
            this.PlayerCancel.OnNext(new PlayerCancelCommand());
        }
        
        public virtual void ExecuteMatchBegan() {
            this.MatchBegan.OnNext(new MatchBeganCommand());
        }
        
        public virtual void ExecuteBeganToPlay() {
            this.BeganToPlay.OnNext(new BeganToPlayCommand());
        }
        
        public virtual void ExecuteBeganToWait() {
            this.BeganToWait.OnNext(new BeganToWaitCommand());
        }
        
        public virtual void ExecuteTurnOn() {
            this.TurnOn.OnNext(new TurnOnCommand());
        }
        
        public virtual void ExecuteTurnOff() {
            this.TurnOff.OnNext(new TurnOffCommand());
        }
        
        public virtual void ExecuteWin() {
            this.Win.OnNext(new WinCommand());
        }
        
        public virtual void ExecuteOver() {
            this.Over.OnNext(new OverCommand());
        }
        
        public virtual void ExecuteInitOK() {
            this.InitOK.OnNext(new InitOKCommand());
        }
        
        public override void Read(ISerializerStream stream) {
            base.Read(stream);
            this._StatusProperty.SetState(stream.DeserializeString("Status"));
            if (stream.DeepSerialize) {
                this.HandCards.Clear();
                this.HandCards.AddRange(stream.DeserializeObjectArray<CardViewModel>("HandCards"));
            }
        }
        
        public override void Write(ISerializerStream stream) {
            base.Write(stream);
            stream.SerializeString("Status", this.Status.Name);;
            if (stream.DeepSerialize) stream.SerializeArray("HandCards", this.HandCards);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
            base.FillCommands(list);
            list.Add(new ViewModelCommandInfo("PlayerReady", PlayerReady) { ParameterType = typeof(void) });
            list.Add(new ViewModelCommandInfo("PlayerCancel", PlayerCancel) { ParameterType = typeof(void) });
            list.Add(new ViewModelCommandInfo("MatchBegan", MatchBegan) { ParameterType = typeof(void) });
            list.Add(new ViewModelCommandInfo("BeganToPlay", BeganToPlay) { ParameterType = typeof(void) });
            list.Add(new ViewModelCommandInfo("BeganToWait", BeganToWait) { ParameterType = typeof(void) });
            list.Add(new ViewModelCommandInfo("TurnOn", TurnOn) { ParameterType = typeof(void) });
            list.Add(new ViewModelCommandInfo("TurnOff", TurnOff) { ParameterType = typeof(void) });
            list.Add(new ViewModelCommandInfo("Win", Win) { ParameterType = typeof(void) });
            list.Add(new ViewModelCommandInfo("Over", Over) { ParameterType = typeof(void) });
            list.Add(new ViewModelCommandInfo("InitOK", InitOK) { ParameterType = typeof(void) });
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_IdProperty, false, false, false, false));
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_StatusProperty, false, false, false, false));
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_PosIdProperty, false, false, false, false));
            list.Add(new ViewModelPropertyInfo(_HandCards, true, true, false, false));
        }
    }
    
    public partial class PlayerViewModel {
        
        public PlayerViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
}
