// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace yigame.epoker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public enum Suit {
        
        SPADE,
        
        HEART,
        
        CLUB,
        
        DIAMOND,
        
        BIG_JOKER,
        
        SMALL_JOKER,
    }
    
    public enum NumericalValue {
        
        NV_ACE,
        
        NV_2,
        
        NV_3,
        
        NV_4,
        
        NV_5,
        
        NV_6,
        
        NV_7,
        
        NV_8,
        
        NV_9,
        
        NV_10,
        
        NV_JACK,
        
        NV_QUEEN,
        
        NV_KING,
        
        NV_SMALL_JOKER,
        
        NV_BIG_JOKER,
    }
    
    public enum CardFace {
        
        FaceUp,
        
        FaceDown,
    }
    
    public enum CardPlace {
        
        Floor,
        
        Hang,
    }
    
    public enum RoomIdentity {
        
        RoomMaster,
        
        RoomGuest,
    }
}
