// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace yigame.epoker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.Serialization;
    using yigame.epoker;
    
    
    public class CardInfoBase : object {
        
        private Suit _Suit;
        
        private NumericalValue _NumericalValue;
        
        public Suit Suit {
            get {
                return _Suit;
            }
            set {
                _Suit = value;
            }
        }
        
        public NumericalValue NumericalValue {
            get {
                return _NumericalValue;
            }
            set {
                _NumericalValue = value;
            }
        }
    }
}
