// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace yigame.epoker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.Serialization;
    
    
    public class NetLoginBase : object {
        
        private String _CustomID;
        
        private Action<string> _SuccessCallback;
        
        private Action<string> _ErrorCallback;
        
        public String CustomID {
            get {
                return _CustomID;
            }
            set {
                _CustomID = value;
            }
        }
        
        public Action<string> SuccessCallback {
            get {
                return _SuccessCallback;
            }
            set {
                _SuccessCallback = value;
            }
        }
        
        public Action<string> ErrorCallback {
            get {
                return _ErrorCallback;
            }
            set {
                _ErrorCallback = value;
            }
        }
    }
    
    public class NetInitBase : object {
    }
    
    public class NetLogoutBase : object {
        
        private Action<string> _SuccessCallback;
        
        private Action<string> _ErrorCallback;
        
        public Action<string> SuccessCallback {
            get {
                return _SuccessCallback;
            }
            set {
                _SuccessCallback = value;
            }
        }
        
        public Action<string> ErrorCallback {
            get {
                return _ErrorCallback;
            }
            set {
                _ErrorCallback = value;
            }
        }
    }
    
    public class NetJoinOrCreateRoomBase : object {
        
        private String _RoomId;
        
        private Action<string> _SuccessCallback;
        
        private Action<string> _ErrorCallback;
        
        public String RoomId {
            get {
                return _RoomId;
            }
            set {
                _RoomId = value;
            }
        }
        
        public Action<string> SuccessCallback {
            get {
                return _SuccessCallback;
            }
            set {
                _SuccessCallback = value;
            }
        }
        
        public Action<string> ErrorCallback {
            get {
                return _ErrorCallback;
            }
            set {
                _ErrorCallback = value;
            }
        }
    }
    
    public class NetLeaveRoomBase : object {
        
        private Action<string> _SuccessCallback;
        
        public Action<string> SuccessCallback {
            get {
                return _SuccessCallback;
            }
            set {
                _SuccessCallback = value;
            }
        }
    }
}
