// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      /Users/EthanW/Documents/UnityProjects/EPoker/Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public partial class GDEItemKeys
    {
        public static string TestSchema_TestSchema001 = "TestSchema001";
        public static string TestSchema_TestSchema002 = "TestSchema002";
        public static string Test2Schema_Test2Schema001 = "Test2Schema001";
    }
}
